# Generated by Django 5.0 on 2023-12-26 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('clinic_name', models.CharField(max_length=100, unique=True, verbose_name='نام کلینیک')),
                ('clinic_address', models.TextField(verbose_name='ادرس کلینیک')),
                ('clinic_postal_code', models.CharField(max_length=11, verbose_name='کد پستی کلینیک')),
                ('clinic_description', models.TextField(verbose_name='توضح در مورد کلینیک')),
                ('is_active_clinic', models.BooleanField(default=True, verbose_name='فعال کلینیک')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع فعالیت')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='پایان کلینیک')),
                ('establishment_date', models.DateField(verbose_name='تاریخ تأسیس')),
                ('doctor_count', models.PositiveIntegerField(default=0, verbose_name='تعداد پزشکان')),
                ('staff_count', models.IntegerField(default=0, verbose_name='تعداد پرسنل')),
            ],
            options={
                'verbose_name': 'clinic',
                'verbose_name_plural': 'clinics',
                'db_table': 'clinic',
            },
        ),
        migrations.CreateModel(
            name='ClinicType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('clinic_type', models.CharField(max_length=100, unique=True, verbose_name='نوع کلینیک')),
                ('clinic_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinic_type', to='clinic.clinic', verbose_name='کلینیک')),
            ],
            options={
                'verbose_name': 'clinic type',
                'verbose_name_plural': 'clinic types',
                'db_table': 'clinic_type',
            },
        ),
        migrations.CreateModel(
            name='ContactClinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('landing_phone', models.CharField(max_length=11, unique=True, verbose_name='تلفن ثابت')),
                ('mobile_phone', models.CharField(max_length=11, unique=True, verbose_name='تلفن موبایل')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='ایمیل')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال بودن')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیح در مورد راه های ارتباطی')),
                ('clinic_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinic_contact', to='clinic.clinic', verbose_name='کلینیک')),
            ],
            options={
                'verbose_name': 'contact clinic',
                'verbose_name_plural': 'contact clinics',
                'db_table': 'contact_clinic',
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('building_permit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='license_building_permit', to='image.images', verbose_name='مجوز ساختمانی')),
                ('clinic_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='license_clinic', to='clinic.clinic', verbose_name='مجوز های کلینیک')),
                ('health_license', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='health_license', to='image.images', verbose_name='مجوز بهداشتی')),
                ('professional_license', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='professional_license', to='image.images', verbose_name='مجوز حرفه ای')),
                ('safety_license', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='license_safety_license', to='image.images', verbose_name='مجوز ایمنی')),
                ('technical_license', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='license_technical_license', to='image.images', verbose_name='مجوز فنی')),
            ],
            options={
                'verbose_name': 'License',
                'verbose_name_plural': 'Licenses',
                'db_table': 'License',
            },
        ),
    ]
