# Generated by Django 5.0 on 2023-12-26 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0002_alter_contactdoctor_facebook_and_more'),
        ('user', '0003_alter_users_is_active_alter_users_is_staff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('users_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('address_patient', models.TextField(verbose_name='آدرس مریض')),
                ('nation_code', models.CharField(max_length=11, unique=True, verbose_name='شماره ملی مریض')),
                ('insurance_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره بیمه')),
                ('blood_type', models.CharField(blank=True, max_length=5, null=True, verbose_name='گروه خون')),
                ('allergies', models.TextField(blank=True, null=True, verbose_name='حساسیت\u200cها')),
                ('medical_history', models.TextField(blank=True, null=True, verbose_name='سوابق پزشکی')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام شخص اضطراری')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=12, null=True, verbose_name='شماره تماس شخص اضطراری')),
                ('occupation', models.CharField(blank=True, max_length=100, null=True, verbose_name='شغل')),
                ('marital_status', models.CharField(blank=True, max_length=20, null=True, verbose_name='وضعیت تاهل')),
                ('referred_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='ارجاع دهنده')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='قد (سانتیمتر)')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='وزن (کیلوگرم)')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient', to='doctors.docktor', verbose_name='دکتر معالج کننده')),
            ],
            options={
                'verbose_name': 'patient',
                'verbose_name_plural': 'patients',
                'db_table': 'patient',
            },
            bases=('user.users', models.Model),
        ),
        migrations.CreateModel(
            name='appointmentDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('from_the_time', models.TimeField(verbose_name='از ساعت')),
                ('at_the_time', models.TimeField(verbose_name='تا ساعت')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_date', to='patient.patient', verbose_name='تاریخ توبت مریض')),
            ],
            options={
                'verbose_name': 'appointmentDate',
                'verbose_name_plural': 'appointmentDates',
                'db_table': 'appointment_date',
            },
        ),
    ]
