# Generated by Django 5.0 on 2023-12-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdoctor',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='فیسبوک'),
        ),
        migrations.AlterField(
            model_name='contactdoctor',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='اینستاگرام'),
        ),
        migrations.AlterField(
            model_name='contactdoctor',
            name='telegram',
            field=models.URLField(blank=True, null=True, verbose_name='تلگرام'),
        ),
        migrations.AlterField(
            model_name='contactdoctor',
            name='twitter',
            field=models.URLField(blank=True, null=True, verbose_name='تویتر'),
        ),
    ]
